# Generated by Django 4.2.13 on 2026-04-22 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="player1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_as_player1",
                to="tournaments.tournamentparticipant",
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_as_player2",
                to="tournaments.tournamentparticipant",
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournamentround",
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to="tournaments.tournamentparticipant",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentround",
            unique_together={("tournament", "round_number")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentparticipant",
            unique_together={("tournament", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentmatch",
            unique_together={("round", "match_number")},
        ),
    ]
