# Generated by Django 4.2.22 on 2026-04-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chess", "0010_add_room_to_match"),
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmatch",
            name="room",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_match",
                to="chess.room",
            ),
        ),
    ]
