# Generated by Django 4.2.22 on 2026-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
