# Generated by Django 4.2.13 on 2026-04-22 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("message", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fen",
                    models.TextField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
                    ),
                ),
                ("pgn", models.TextField(blank=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("white", "White wins"),
                            ("black", "Black wins"),
                            ("draw", "Draw"),
                            ("ongoing", "Ongoing"),
                            ("aborted", "Aborted"),
                        ],
                        default="ongoing",
                        max_length=10,
                    ),
                ),
                ("white_time_remaining", models.IntegerField(default=600)),
                ("black_time_remaining", models.IntegerField(default=600)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_number", models.IntegerField()),
                (
                    "san",
                    models.CharField(
                        help_text="Standard Algebraic Notation, e.g. e4, Nf3",
                        max_length=10,
                    ),
                ),
                (
                    "uci",
                    models.CharField(help_text="UCI format, e.g. e2e4", max_length=10),
                ),
                ("fen_after", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["move_number"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "time_control",
                    models.IntegerField(default=600, help_text="Seconds per player"),
                ),
                (
                    "increment",
                    models.IntegerField(default=0, help_text="Seconds added per move"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
