# Generated by Django 4.2.22 on 2026-04-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chess", "0004_platformsettings_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ratings_updated",
            field=models.BooleanField(default=False),
        ),
    ]
