# Generated by Django 4.2.22 on 2026-04-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chess", "0008_paid_challenge_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_rating_change",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="white_rating_change",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="challenge_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Ücretli challenge kazançlarından alınan platform komisyonu (%). Örn: 10 → %10",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="paid_challenges_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Ücretli challenge sistemini aktif eder. Stripe entegrasyonu gerektirir.",
            ),
        ),
    ]
